# Generate refresh tokens for users that don't have any.

from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand

from refreshtoken.models import RefreshToken
from refreshtoken.settings import api_settings as jwt_refresh_settings


class Command(BaseCommand):
    """
    Generate a token for all users in all databases.

    The refresh token 'key' is automatically generated by the 'refreshtoken'
    app.
    Refresh tokens are only generated for a user if the user does not have one.
    """

    help = 'Generate refresh tokens for all users without refresh tokens.'

    def handle(self, *args, **kwargs):
        for user in (
                get_user_model().objects
                .filter(refresh_tokens__isnull=True)):
            RefreshToken.objects.create(
                user=user, app=jwt_refresh_settings.JWT_APP_NAME).save()
            self.stdout.write('Created refresh token for {}'.format(user))
